<a href="https://colab.research.google.com/github/NiharikaAmritkar/AI-ML/blob/main/ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [ ]:
dataset= pd.read_csv('/content/Churn_Modelling.csv')
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [ ]:
x= dataset.iloc[:, 3: 13].values
y= dataset.iloc[:, 13].values

In [ ]:
#encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_x1= LabelEncoder()
x[:, 1]= labelencoder_x1.fit_transform(x[:, 1])

In [ ]:
labelencoder_x2= LabelEncoder()
x[:, 2]= labelencoder_x2.fit_transform(x[:, 2])

In [ ]:
x

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [ ]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
columnTransformer = ColumnTransformer([('encoder', OneHotEncoder(), [1])],     remainder='passthrough')
x=np.array(columnTransformer.fit_transform(x),dtype=np.str)

<ipython-input-7-7fb9809a22c6>:4: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x=np.array(columnTransformer.fit_transform(x),dtype=np.str)


In [ ]:
print(x)

[['1.0' '0.0' '0.0' ... '1' '1' '101348.88']
 ['0.0' '0.0' '1.0' ... '0' '1' '112542.58']
 ['1.0' '0.0' '0.0' ... '1' '0' '113931.57']
 ...
 ['1.0' '0.0' '0.0' ... '0' '1' '42085.58']
 ['0.0' '1.0' '0.0' ... '1' '0' '92888.52']
 ['1.0' '0.0' '0.0' ... '1' '0' '38190.78']]


In [ ]:
x= x[:, 1:]

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.2, random_state= 0)

In [ ]:
#feature scaling
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
x_train= sc.fit_transform(x_train)
x_test= sc.transform(x_test)

In [ ]:
import keras

In [ ]:
from keras.models import Sequential #used to initialize NN
from keras.layers import Dense #used to create layers


In [ ]:
#initializing ANN
classifier= Sequential()

In [ ]:
#adding input layer and first hidden layer
classifier.add(Dense(6, activation= 'relu', input_dim= 11)) #output_dim is no. of nodes in the hidden layer, init is the initializing method, 11 bcoz we have 11 indeoendent variables

In [ ]:
#adding 2nd hidden layer
classifier.add(Dense(6, activation= 'relu'))

In [ ]:
#adding output layer
classifier.add(Dense(1, activation= 'sigmoid'))

In [ ]:
#compiling the model
classifier.compile(optimizer= 'adam', loss='binary_crossentropy', metrics= ['accuracy'])


In [ ]:
#fitting the ANN to the training set
classifier.fit(x_train, y_train, batch_size=10, epochs= 100)

Epoch 1/100
800/800 [==============================] - 8s 3ms/step - loss: 0.5820 - accuracy: 0.7206
Epoch 2/100
800/800 [==============================] - 2s 3ms/step - loss: 0.4473 - accuracy: 0.8015
Epoch 3/100
800/800 [==============================] - 2s 3ms/step - loss: 0.4308 - accuracy: 0.8084
Epoch 4/100
800/800 [==============================] - 2s 3ms/step - loss: 0.4199 - accuracy: 0.8136
Epoch 5/100
800/800 [==============================] - 2s 3ms/step - loss: 0.4017 - accuracy: 0.8245
Epoch 6/100
800/800 [==============================] - 2s 3ms/step - loss: 0.3805 - accuracy: 0.8388
Epoch 7/100
800/800 [==============================] - 3s 3ms/step - loss: 0.3664 - accuracy: 0.8446
Epoch 8/100
800/800 [==============================] - 2s 3ms/step - loss: 0.3590 - accuracy: 0.8472
Epoch 9/100
800/800 [==============================] - 2s 3ms/step - loss: 0.3546 - accuracy: 0.8515
Epoch 10/100
800/800 [==============================] - 2s 3ms/step - loss: 0.3518 - accura

In [ ]:
#predicting the test set results, predicting the probabilites
y_pred= classifier.predict(x_test)

63/63 [==============================] - 0s 3ms/step


In [ ]:
y_pred= (y_pred>0.5)

In [ ]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [ ]:
#creating confusion matrix
from sklearn.metrics import confusion_matrix
cm= confusion_matrix(y_test, y_pred)
cm

array([[1497,   98],
       [ 197,  208]])